[tox]
minversion = 3.8.0
envlist =
  format
  lint
  poetry
  py{38,39,310,311,312,313,314}
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
  poetry
  pip
setenv =
  COV_FAIL_UNDER = 100
skip_install = true
sitepackages = false
commands_pre =
  poetry install --all-extras
  pip install pytest-xdist
commands =
  pytest -o 'addopts=--cov-config .coveragerc --cov=duffy --cov-report term --cov-report xml --cov-report html -n auto --cov-fail-under {env:COV_FAIL_UNDER}' tests/

[testenv:py39]
# Python 3.9 fails tracing an async generator to its completion in create_session()
setenv =
  COV_FAIL_UNDER = 99

[testenv:format]
deps = ruff
commands_pre =
commands = ruff format --diff duffy/ tests/

[testenv:lint]
deps = ruff
commands_pre =
commands = ruff check duffy/ tests/

[testenv:poetry]
deps = poetry
commands_pre =
commands = poetry check --lock

[flake8]
max-line-length = 100
