"""Add a version column to the stock table so we can guard against concurrent
updates

Revision ID: 1023d405677d
Revises: 688abba1b8da
Create Date: 2018-08-28 11:23:08.684903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1023d405677d'
down_revision = '688abba1b8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
