"""Add a flavor column to the Hosts

Revision ID: bb1e6f5b121a
Revises: 41eed8ffdefc
Create Date: 2017-11-08 00:27:42.228961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1e6f5b121a'
down_revision = '41eed8ffdefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('flavor')

    # ### end Alembic commands ###
