---
- tags:
    - postgresql/server
  block:
    - name: Import distro-specific variables
      include_vars: "{{ item }}"
      register: included_file
      failed_when: >-
        included_file.ansible_included_var_files | length > 0 and not included_file.ansible_facts
      loop:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"

    - name: Install PostgreSQL server packages
      package:
        name: "{{ postgresql_server_packages | list }}"
        state: present
      tags:
        - packages

    - name: Set up PostgreSQL initially
      command:
        cmd: postgresql-setup --initdb
        creates: /var/lib/pgsql/data/postgresql.conf
      tags:
        - config

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql.service
        enabled: yes
        state: started
      tags:
        - services
