---
- hosts: duffy_server
  become: yes
  become_user: duffy
  environment:
    PATH: "{{ duffy_home | default('/home/duffy') }}/bin:{{ ansible_env.PATH }}"
  vars:
    _virtualenv: "{{ virtualenv | default('/srv/duffy') }}"
  tasks:
    - name: Verify duffy_tenant is set
      fail:
        msg: "The duffy_tenant variable must be set"
      when: duffy_tenant is not defined

    - name: Set ssh_key default
      set_fact:
        ssh_key: "## SSH key not set"
      when: ssh_key is not defined

    - name: "Verify variables don't contain quotes"
      fail:
        msg: "The {{ item }} variable must not contain quotes."
      when: >-
        lookup('vars', item, default=omit) != omit
        and ("'" in lookup('vars', item) or '"' in lookup('vars', item))
      loop:
        - duffy_tenant
        - ssh_key

    - name: Check if tenant exists
      command:
        argv:
          - psql
          - duffy
          - "-qtAc"
          - "SELECT COUNT(name) FROM tenants WHERE name='{{ duffy_tenant }}';"
      changed_when: no
      register: tenant_exists

    - when: tenant_exists.stdout == "0"
      block:
        - name: Create an API key
          command: uuidgen --random
          register: uuidgen_out

        - name: Compute bcrypt hash of API key
          command:
            argv:
              - "{{ _virtualenv }}/bin/python"
              - "-c"
              - |
                import bcrypt
                print(
                    bcrypt.hashpw(
                        "{{ uuidgen_out.stdout }}".encode("ascii"),
                        bcrypt.gensalt(),
                    ).decode("ascii"),
                    end="",
                )
          register: bcrypt_out

        - name: "Create {{ duffy_tenant }} tenant for Duffy"
          command:
            argv:
              - psql
              - duffy
              - "-qtAc"
              - >-
                INSERT INTO tenants (name, is_admin, ssh_key, api_key)
                VALUES (
                  '{{ duffy_tenant }}',
                  TRUE,
                  '{{ ssh_key }}',
                  '{{ bcrypt_out.stdout }}'
                );

        - name: Summary
          debug:
            msg: "Created {{ duffy_tenant }} tenant with API key: {{ uuidgen_out.stdout }}"
